/home/zcw7438/.local/lib/python3.6/site-packages/pandas/compat/_optional.py:106: UserWarning: Pandas requires version '1.2.1' or newer of 'bottleneck' (version '1.2.0' currently installed).
  warnings.warn(msg, UserWarning)
   Unnamed: 0  Unnamed: 0.1       upc  ...  CANDY  GUM  dma_code_month
0           0             0  10000001  ...      1    0      529 200601
1           1             1  10000001  ...      1    0      529 200603
2           2             2  10000001  ...      1    0      561 200902
3           3             3  10000001  ...      1    0      618 200601
4           4             4  10000001  ...      1    0      640 200602

[5 rows x 46 columns]
   Unnamed: 0  Unnamed: 0.1       upc  ...  CANDY  GUM  dma_code_month
0           0             0  10000001  ...      1    0      529 200601
1           1             1  10000001  ...      1    0      529 200603
3           3             3  10000001  ...      1    0      618 200601
4           4             4  10000001  ...      1    0      640 200602
6           6             6  10000001  ...      1    0      693 200603

[5 rows x 46 columns]
  dma_code_month  dma_code  ... mint  chocolate
0     529 200601       529  ...    0          0
1     529 200603       529  ...    0          0
3     618 200601       618  ...    0          0
4     640 200602       640  ...    0          0
6     693 200603       693  ...    0          0

[5 rows x 14 columns]
Empty DataFrame
Columns: [dma_code_month, dma_code, owner initial, log_adjusted_price, upc, market_share, distance, time, CANDY, GUM, sugar, cocoa_beans, mint, chocolate]
Index: []
Initializing the problem ...
Traceback (most recent call last):
  File "plainLogit.py", line 52, in <module>
    GenerateDEData(products, quarterOrMonth, inputs, characteristics)
  File "plainLogit.py", line 24, in GenerateDEData
    problem = pyblp.Problem(logit_formulation, demand_estimation_data)
  File "/home/zcw7438/.local/lib/python3.6/site-packages/pyblp/economies/problem.py", line 1193, in __init__
    products = Products(product_formulations, product_data, add_exogenous=add_exogenous)
  File "/home/zcw7438/.local/lib/python3.6/site-packages/pyblp/primitives.py", line 140, in __new__
    raise KeyError("product_data must have a market_ids field.")
KeyError: 'product_data must have a market_ids field.'
